docker_builder:
  env:
    - FLUTTER_VERSION: "3.29.0"
    - DOCKER_TAG: "latest"
  build_script:
    - docker build -t ghcr.io/your-repo/flutter-sdk:$DOCKER_TAG --build-arg FLUTTER_VERSION=$FLUTTER_VERSION sdk
    - docker push ghcr.io/your-repo/flutter-sdk:$DOCKER_TAG
