name: "Check Flutter Stable Version"
on:
  schedule:
    # Run every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_stable_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install yq and jq
        run: |
          mkdir -p ~/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
          chmod +x ~/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH
          sudo apt-get install -y jq curl
      - name: Check for new Stable Flutter version
        run: sh scripts/update_flutter_version.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: Update Stable Flutter version"
          title: "chore: Update Stable Flutter version"
          branch: "chore/update-flutter-stable"
